const actionTypes = {
  loginRequest: 'loginRequest',
  loginSuccessfull: 'loginSuccessfull',
  loginFail: 'loginFail',
  logout: 'logout',
  addProductRequest: 'addProductRequest',
  addProductSuccessfull: 'addProductSuccessfull',
  addProductFail: 'addProductFail',
  deleteProductRequest: 'deleteProductRequest',
  deleteProductSuccessfull: 'deleteProductSuccessfull',
  deleteProductFail: 'deleteProductFail',
  editProductRequest: 'editProductRequest',
  editProductSuccessfull: 'editProductSuccessfull',
  editProductFail: 'editProductFail',
  getProductRequest: 'getProductRequest',
  getProductSuccessfull: 'getProductSuccessfull',
  getProductFail: 'getProductFail',
  getNewsRequest: 'getNewsRequest',
  getNewsSuccessfull: 'getNewsSuccessfull',
  getNewsFail: 'getNewsFail',
  createNewsRequest: 'createNewsRequest',
  createNewsSuccessfull: 'createNewsSuccessfull',
  createNewsFail: 'createNewsFail',
  removeNewsRequest: 'removeNewsRequest',
  removeNewsSuccess: 'removeNewsSuccess',
  removeNewsFail: 'removeNewsFail',
  customerEmailRequest: 'customerEmailRequest',
  customerEmailSuccessfully: 'customerEmailSuccessfully',
  customerEmailFail: 'customerEmailFail',
  getAllOrderRequest: 'getAllOrderRequest',
  getAllOrderSuccessfully: 'getAllOrderSuccessfully',
  getAllOrderFail: 'getAllOrderFail',
  getNewOrderRequest: 'getNewOrderRequest',
  getNewOrderSuccessfully: 'getNewOrderSuccessfully',
  getNewOrderFail: 'getNewOrderFail',
  orderDelivered: 'orderDelivered',
}

export default actionTypes
